spring:
  datasource.url: jdbc:h2:file:./camunda-h2-database;AUTO_SERVER=TRUE
  application.name: operaton-engine
operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
    client:
      base-url: http://localhost:8080/engine-rest
      worker-id: ${spring.application.name}-${random.uuid}
      max-tasks: 10
      lock-duration: 60000
      async-response-timeout: 30000